name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to local server
        run: |
          curl -X POST https://851f-116-41-49-181.ngrok-free.app/api/deploy
