name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to local server
        run: |
          curl -X POST http://<LOCAL_SERVER_IP>:3000/api/deploy
